GET http://localhost:4000/visitlist

###

POST http://localhost:4000/searchlist
Content-Type: application/json

{
    "name": "John Doe"
}

###

POST http://localhost:4000/appointment
Content-Type: application/json

{
  "newname": "John Doe",
  "newcompany": "ABC Corporation",
  "newpurpose": "Meeting",
  "newphoneNumber": "1234567890",
  "newdate": "2023-06-15",
  "newtime": "10:00 AM",
  "newuser": {
    "name": "Jane Smith",
    "email": "janesmith@example.com",
    "role": "Manager"
  }
}